import numpy as np
from typing import List, Tuple
from typing import Union, Any

from .ModelML import ModelML
from ..Json.JsonFileHander import JsonFileHandler
from sklearn.linear_model import LogisticRegression

class LR(ModelML):
    """
    Random Forest (RF) model for classification.

    Parameters:
    -----------
    Input_shape : tuple[int, ...]
        The shape of the input data, excluding the batch size.
    Output_shape : tuple[int, ...]
        The shape of the output data, excluding the batch size.
    JSON_file : str
        The path to the JSON file containing the model architecture.

    Methods:
    --------
    fit_model():
        Trains the RF model.
    predict_model(Model, Array) -> Union[None, Any]:
        Makes predictions with the RF model.

    """

    def __init__(
        self, 
        Input_shape: Tuple[int, ...],
        Output_shape : Tuple[int, ...]
    ):
        """
        RF class constructor.

        Parameters:
        -----------
        Input_shape : Tuple[int, ...]
            Tuple containing the shape of the input data.
        Output_shape : Tuple[int, ...]
            Tuple containing the shape of the output data.
        JSON_file : str
            File containing the model architecture in JSON format.

        Returns:
        --------
        None
        """

        self.Input_shape = Input_shape;
        self.Output_shape = Output_shape;
        
        self.Model = LogisticRegression(max_iter = 20000);

    def fit_model(self):
        """
        Train the random forest.

        Parameters:
        -----------
        None

        Returns:
        --------
        Tuple[Any, Dict[str, Any]]
            A tuple containing the trained model and history data.
        """
        return self.Model.fit(
            self.Input_shape, 
            self.Output_shape
        );
    
    @staticmethod
    def predict_model(Model, Array : np.ndarray) -> Union[None, Any]:
        """
        Generate predictions for input data using the trained model.

        Parameters:
        -----------
        Array : np.ndarray
            Input data for which predictions are to be generated.

        Returns:
        --------
        Union[None, Any]
            Prediction generated by the neural network model.
        """

        return Model.predict(Array)
    
